// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phone.proto

package com.shujia.hbase;

public final class Phone {
  private Phone() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface phoneOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string phoneNum = 1;
    /**
     * <code>required string phoneNum = 1;</code>
     */
    boolean hasPhoneNum();
    /**
     * <code>required string phoneNum = 1;</code>
     */
    java.lang.String getPhoneNum();
    /**
     * <code>required string phoneNum = 1;</code>
     */
    com.google.protobuf.ByteString
        getPhoneNumBytes();

    // required string time = 2;
    /**
     * <code>required string time = 2;</code>
     */
    boolean hasTime();
    /**
     * <code>required string time = 2;</code>
     */
    java.lang.String getTime();
    /**
     * <code>required string time = 2;</code>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    // required string dpNum = 3;
    /**
     * <code>required string dpNum = 3;</code>
     */
    boolean hasDpNum();
    /**
     * <code>required string dpNum = 3;</code>
     */
    java.lang.String getDpNum();
    /**
     * <code>required string dpNum = 3;</code>
     */
    com.google.protobuf.ByteString
        getDpNumBytes();

    // required int32 type = 4;
    /**
     * <code>required int32 type = 4;</code>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 4;</code>
     */
    int getType();
  }
  /**
   * Protobuf type {@code com.sxt.hbase.phone}
   */
  public static final class phone extends
      com.google.protobuf.GeneratedMessage
      implements phoneOrBuilder {
    // Use phone.newBuilder() to construct.
    private phone(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private phone(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final phone defaultInstance;
    public static phone getDefaultInstance() {
      return defaultInstance;
    }

    public phone getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private phone(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              phoneNum_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              time_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              dpNum_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              type_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shujia.hbase.Phone.internal_static_com_sxt_hbase_phone_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shujia.hbase.Phone.internal_static_com_sxt_hbase_phone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shujia.hbase.Phone.phone.class, com.shujia.hbase.Phone.phone.Builder.class);
    }

    public static com.google.protobuf.Parser<phone> PARSER =
        new com.google.protobuf.AbstractParser<phone>() {
      public phone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new phone(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<phone> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string phoneNum = 1;
    public static final int PHONENUM_FIELD_NUMBER = 1;
    private java.lang.Object phoneNum_;
    /**
     * <code>required string phoneNum = 1;</code>
     */
    public boolean hasPhoneNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string phoneNum = 1;</code>
     */
    public java.lang.String getPhoneNum() {
      java.lang.Object ref = phoneNum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          phoneNum_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string phoneNum = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneNumBytes() {
      java.lang.Object ref = phoneNum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string time = 2;
    public static final int TIME_FIELD_NUMBER = 2;
    private java.lang.Object time_;
    /**
     * <code>required string time = 2;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string time = 2;</code>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          time_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string time = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string dpNum = 3;
    public static final int DPNUM_FIELD_NUMBER = 3;
    private java.lang.Object dpNum_;
    /**
     * <code>required string dpNum = 3;</code>
     */
    public boolean hasDpNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string dpNum = 3;</code>
     */
    public java.lang.String getDpNum() {
      java.lang.Object ref = dpNum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dpNum_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string dpNum = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDpNumBytes() {
      java.lang.Object ref = dpNum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dpNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 type = 4;
    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>required int32 type = 4;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 type = 4;</code>
     */
    public int getType() {
      return type_;
    }

    private void initFields() {
      phoneNum_ = "";
      time_ = "";
      dpNum_ = "";
      type_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPhoneNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDpNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPhoneNumBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDpNumBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, type_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPhoneNumBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDpNumBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.shujia.hbase.Phone.phone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shujia.hbase.Phone.phone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shujia.hbase.Phone.phone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shujia.hbase.Phone.phone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shujia.hbase.Phone.phone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.shujia.hbase.Phone.phone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.shujia.hbase.Phone.phone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.shujia.hbase.Phone.phone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.shujia.hbase.Phone.phone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.shujia.hbase.Phone.phone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.shujia.hbase.Phone.phone prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sxt.hbase.phone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.shujia.hbase.Phone.phoneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.shujia.hbase.Phone.internal_static_com_sxt_hbase_phone_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.shujia.hbase.Phone.internal_static_com_sxt_hbase_phone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.shujia.hbase.Phone.phone.class, com.shujia.hbase.Phone.phone.Builder.class);
      }

      // Construct using com.sxt.hbase.Phone.phone.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        phoneNum_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        dpNum_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.shujia.hbase.Phone.internal_static_com_sxt_hbase_phone_descriptor;
      }

      public com.shujia.hbase.Phone.phone getDefaultInstanceForType() {
        return com.shujia.hbase.Phone.phone.getDefaultInstance();
      }

      public com.shujia.hbase.Phone.phone build() {
        com.shujia.hbase.Phone.phone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.shujia.hbase.Phone.phone buildPartial() {
        com.shujia.hbase.Phone.phone result = new com.shujia.hbase.Phone.phone(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.phoneNum_ = phoneNum_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dpNum_ = dpNum_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.shujia.hbase.Phone.phone) {
          return mergeFrom((com.shujia.hbase.Phone.phone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.shujia.hbase.Phone.phone other) {
        if (other == com.shujia.hbase.Phone.phone.getDefaultInstance()) return this;
        if (other.hasPhoneNum()) {
          bitField0_ |= 0x00000001;
          phoneNum_ = other.phoneNum_;
          onChanged();
        }
        if (other.hasTime()) {
          bitField0_ |= 0x00000002;
          time_ = other.time_;
          onChanged();
        }
        if (other.hasDpNum()) {
          bitField0_ |= 0x00000004;
          dpNum_ = other.dpNum_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPhoneNum()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        if (!hasDpNum()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.shujia.hbase.Phone.phone parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.shujia.hbase.Phone.phone) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string phoneNum = 1;
      private java.lang.Object phoneNum_ = "";
      /**
       * <code>required string phoneNum = 1;</code>
       */
      public boolean hasPhoneNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string phoneNum = 1;</code>
       */
      public java.lang.String getPhoneNum() {
        java.lang.Object ref = phoneNum_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          phoneNum_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string phoneNum = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneNumBytes() {
        java.lang.Object ref = phoneNum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneNum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string phoneNum = 1;</code>
       */
      public Builder setPhoneNum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        phoneNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string phoneNum = 1;</code>
       */
      public Builder clearPhoneNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        phoneNum_ = getDefaultInstance().getPhoneNum();
        onChanged();
        return this;
      }
      /**
       * <code>required string phoneNum = 1;</code>
       */
      public Builder setPhoneNumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        phoneNum_ = value;
        onChanged();
        return this;
      }

      // required string time = 2;
      private java.lang.Object time_ = "";
      /**
       * <code>required string time = 2;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string time = 2;</code>
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string time = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string time = 2;</code>
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 2;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 2;</code>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }

      // required string dpNum = 3;
      private java.lang.Object dpNum_ = "";
      /**
       * <code>required string dpNum = 3;</code>
       */
      public boolean hasDpNum() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string dpNum = 3;</code>
       */
      public java.lang.String getDpNum() {
        java.lang.Object ref = dpNum_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          dpNum_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string dpNum = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDpNumBytes() {
        java.lang.Object ref = dpNum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dpNum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string dpNum = 3;</code>
       */
      public Builder setDpNum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dpNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string dpNum = 3;</code>
       */
      public Builder clearDpNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dpNum_ = getDefaultInstance().getDpNum();
        onChanged();
        return this;
      }
      /**
       * <code>required string dpNum = 3;</code>
       */
      public Builder setDpNumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dpNum_ = value;
        onChanged();
        return this;
      }

      // required int32 type = 4;
      private int type_ ;
      /**
       * <code>required int32 type = 4;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 type = 4;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 4;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 4;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.sxt.hbase.phone)
    }

    static {
      defaultInstance = new phone(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.sxt.hbase.phone)
  }

  public interface datePhoneListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.sxt.hbase.phone datePhone = 1;
    /**
     * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
     */
    java.util.List<com.shujia.hbase.Phone.phone>
        getDatePhoneList();
    /**
     * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
     */
    com.shujia.hbase.Phone.phone getDatePhone(int index);
    /**
     * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
     */
    int getDatePhoneCount();
    /**
     * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
     */
    java.util.List<? extends com.shujia.hbase.Phone.phoneOrBuilder>
        getDatePhoneOrBuilderList();
    /**
     * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
     */
    com.shujia.hbase.Phone.phoneOrBuilder getDatePhoneOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.sxt.hbase.datePhoneList}
   */
  public static final class datePhoneList extends
      com.google.protobuf.GeneratedMessage
      implements datePhoneListOrBuilder {
    // Use datePhoneList.newBuilder() to construct.
    private datePhoneList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private datePhoneList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final datePhoneList defaultInstance;
    public static datePhoneList getDefaultInstance() {
      return defaultInstance;
    }

    public datePhoneList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private datePhoneList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                datePhone_ = new java.util.ArrayList<com.shujia.hbase.Phone.phone>();
                mutable_bitField0_ |= 0x00000001;
              }
              datePhone_.add(input.readMessage(com.shujia.hbase.Phone.phone.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          datePhone_ = java.util.Collections.unmodifiableList(datePhone_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shujia.hbase.Phone.internal_static_com_sxt_hbase_datePhoneList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shujia.hbase.Phone.internal_static_com_sxt_hbase_datePhoneList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shujia.hbase.Phone.datePhoneList.class, com.shujia.hbase.Phone.datePhoneList.Builder.class);
    }

    public static com.google.protobuf.Parser<datePhoneList> PARSER =
        new com.google.protobuf.AbstractParser<datePhoneList>() {
      public datePhoneList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new datePhoneList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<datePhoneList> getParserForType() {
      return PARSER;
    }

    // repeated .com.sxt.hbase.phone datePhone = 1;
    public static final int DATEPHONE_FIELD_NUMBER = 1;
    private java.util.List<com.shujia.hbase.Phone.phone> datePhone_;
    /**
     * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
     */
    public java.util.List<com.shujia.hbase.Phone.phone> getDatePhoneList() {
      return datePhone_;
    }
    /**
     * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
     */
    public java.util.List<? extends com.shujia.hbase.Phone.phoneOrBuilder>
        getDatePhoneOrBuilderList() {
      return datePhone_;
    }
    /**
     * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
     */
    public int getDatePhoneCount() {
      return datePhone_.size();
    }
    /**
     * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
     */
    public com.shujia.hbase.Phone.phone getDatePhone(int index) {
      return datePhone_.get(index);
    }
    /**
     * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
     */
    public com.shujia.hbase.Phone.phoneOrBuilder getDatePhoneOrBuilder(
        int index) {
      return datePhone_.get(index);
    }

    private void initFields() {
      datePhone_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getDatePhoneCount(); i++) {
        if (!getDatePhone(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < datePhone_.size(); i++) {
        output.writeMessage(1, datePhone_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < datePhone_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, datePhone_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.shujia.hbase.Phone.datePhoneList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shujia.hbase.Phone.datePhoneList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shujia.hbase.Phone.datePhoneList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shujia.hbase.Phone.datePhoneList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shujia.hbase.Phone.datePhoneList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.shujia.hbase.Phone.datePhoneList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.shujia.hbase.Phone.datePhoneList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.shujia.hbase.Phone.datePhoneList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.shujia.hbase.Phone.datePhoneList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.shujia.hbase.Phone.datePhoneList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.shujia.hbase.Phone.datePhoneList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sxt.hbase.datePhoneList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.shujia.hbase.Phone.datePhoneListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.shujia.hbase.Phone.internal_static_com_sxt_hbase_datePhoneList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.shujia.hbase.Phone.internal_static_com_sxt_hbase_datePhoneList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.shujia.hbase.Phone.datePhoneList.class, com.shujia.hbase.Phone.datePhoneList.Builder.class);
      }

      // Construct using com.sxt.hbase.Phone.datePhoneList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDatePhoneFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (datePhoneBuilder_ == null) {
          datePhone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          datePhoneBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.shujia.hbase.Phone.internal_static_com_sxt_hbase_datePhoneList_descriptor;
      }

      public com.shujia.hbase.Phone.datePhoneList getDefaultInstanceForType() {
        return com.shujia.hbase.Phone.datePhoneList.getDefaultInstance();
      }

      public com.shujia.hbase.Phone.datePhoneList build() {
        com.shujia.hbase.Phone.datePhoneList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.shujia.hbase.Phone.datePhoneList buildPartial() {
        com.shujia.hbase.Phone.datePhoneList result = new com.shujia.hbase.Phone.datePhoneList(this);
        int from_bitField0_ = bitField0_;
        if (datePhoneBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            datePhone_ = java.util.Collections.unmodifiableList(datePhone_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.datePhone_ = datePhone_;
        } else {
          result.datePhone_ = datePhoneBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.shujia.hbase.Phone.datePhoneList) {
          return mergeFrom((com.shujia.hbase.Phone.datePhoneList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.shujia.hbase.Phone.datePhoneList other) {
        if (other == com.shujia.hbase.Phone.datePhoneList.getDefaultInstance()) return this;
        if (datePhoneBuilder_ == null) {
          if (!other.datePhone_.isEmpty()) {
            if (datePhone_.isEmpty()) {
              datePhone_ = other.datePhone_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDatePhoneIsMutable();
              datePhone_.addAll(other.datePhone_);
            }
            onChanged();
          }
        } else {
          if (!other.datePhone_.isEmpty()) {
            if (datePhoneBuilder_.isEmpty()) {
              datePhoneBuilder_.dispose();
              datePhoneBuilder_ = null;
              datePhone_ = other.datePhone_;
              bitField0_ = (bitField0_ & ~0x00000001);
              datePhoneBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDatePhoneFieldBuilder() : null;
            } else {
              datePhoneBuilder_.addAllMessages(other.datePhone_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getDatePhoneCount(); i++) {
          if (!getDatePhone(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.shujia.hbase.Phone.datePhoneList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.shujia.hbase.Phone.datePhoneList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.sxt.hbase.phone datePhone = 1;
      private java.util.List<com.shujia.hbase.Phone.phone> datePhone_ =
        java.util.Collections.emptyList();
      private void ensureDatePhoneIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          datePhone_ = new java.util.ArrayList<com.shujia.hbase.Phone.phone>(datePhone_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.shujia.hbase.Phone.phone, com.shujia.hbase.Phone.phone.Builder, com.shujia.hbase.Phone.phoneOrBuilder> datePhoneBuilder_;

      /**
       * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
       */
      public java.util.List<com.shujia.hbase.Phone.phone> getDatePhoneList() {
        if (datePhoneBuilder_ == null) {
          return java.util.Collections.unmodifiableList(datePhone_);
        } else {
          return datePhoneBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
       */
      public int getDatePhoneCount() {
        if (datePhoneBuilder_ == null) {
          return datePhone_.size();
        } else {
          return datePhoneBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
       */
      public com.shujia.hbase.Phone.phone getDatePhone(int index) {
        if (datePhoneBuilder_ == null) {
          return datePhone_.get(index);
        } else {
          return datePhoneBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
       */
      public Builder setDatePhone(
          int index, com.shujia.hbase.Phone.phone value) {
        if (datePhoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatePhoneIsMutable();
          datePhone_.set(index, value);
          onChanged();
        } else {
          datePhoneBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
       */
      public Builder setDatePhone(
          int index, com.shujia.hbase.Phone.phone.Builder builderForValue) {
        if (datePhoneBuilder_ == null) {
          ensureDatePhoneIsMutable();
          datePhone_.set(index, builderForValue.build());
          onChanged();
        } else {
          datePhoneBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
       */
      public Builder addDatePhone(com.shujia.hbase.Phone.phone value) {
        if (datePhoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatePhoneIsMutable();
          datePhone_.add(value);
          onChanged();
        } else {
          datePhoneBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
       */
      public Builder addDatePhone(
          int index, com.shujia.hbase.Phone.phone value) {
        if (datePhoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatePhoneIsMutable();
          datePhone_.add(index, value);
          onChanged();
        } else {
          datePhoneBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
       */
      public Builder addDatePhone(
          com.shujia.hbase.Phone.phone.Builder builderForValue) {
        if (datePhoneBuilder_ == null) {
          ensureDatePhoneIsMutable();
          datePhone_.add(builderForValue.build());
          onChanged();
        } else {
          datePhoneBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
       */
      public Builder addDatePhone(
          int index, com.shujia.hbase.Phone.phone.Builder builderForValue) {
        if (datePhoneBuilder_ == null) {
          ensureDatePhoneIsMutable();
          datePhone_.add(index, builderForValue.build());
          onChanged();
        } else {
          datePhoneBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
       */
      public Builder addAllDatePhone(
          java.lang.Iterable<? extends com.shujia.hbase.Phone.phone> values) {
        if (datePhoneBuilder_ == null) {
          ensureDatePhoneIsMutable();
          super.addAll(values, datePhone_);
          onChanged();
        } else {
          datePhoneBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
       */
      public Builder clearDatePhone() {
        if (datePhoneBuilder_ == null) {
          datePhone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          datePhoneBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
       */
      public Builder removeDatePhone(int index) {
        if (datePhoneBuilder_ == null) {
          ensureDatePhoneIsMutable();
          datePhone_.remove(index);
          onChanged();
        } else {
          datePhoneBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
       */
      public com.shujia.hbase.Phone.phone.Builder getDatePhoneBuilder(
          int index) {
        return getDatePhoneFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
       */
      public com.shujia.hbase.Phone.phoneOrBuilder getDatePhoneOrBuilder(
          int index) {
        if (datePhoneBuilder_ == null) {
          return datePhone_.get(index);  } else {
          return datePhoneBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
       */
      public java.util.List<? extends com.shujia.hbase.Phone.phoneOrBuilder>
           getDatePhoneOrBuilderList() {
        if (datePhoneBuilder_ != null) {
          return datePhoneBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(datePhone_);
        }
      }
      /**
       * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
       */
      public com.shujia.hbase.Phone.phone.Builder addDatePhoneBuilder() {
        return getDatePhoneFieldBuilder().addBuilder(
            com.shujia.hbase.Phone.phone.getDefaultInstance());
      }
      /**
       * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
       */
      public com.shujia.hbase.Phone.phone.Builder addDatePhoneBuilder(
          int index) {
        return getDatePhoneFieldBuilder().addBuilder(
            index, com.shujia.hbase.Phone.phone.getDefaultInstance());
      }
      /**
       * <code>repeated .com.sxt.hbase.phone datePhone = 1;</code>
       */
      public java.util.List<com.shujia.hbase.Phone.phone.Builder>
           getDatePhoneBuilderList() {
        return getDatePhoneFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.shujia.hbase.Phone.phone, com.shujia.hbase.Phone.phone.Builder, com.shujia.hbase.Phone.phoneOrBuilder>
          getDatePhoneFieldBuilder() {
        if (datePhoneBuilder_ == null) {
          datePhoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.shujia.hbase.Phone.phone, com.shujia.hbase.Phone.phone.Builder, com.shujia.hbase.Phone.phoneOrBuilder>(
                  datePhone_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          datePhone_ = null;
        }
        return datePhoneBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.sxt.hbase.datePhoneList)
    }

    static {
      defaultInstance = new datePhoneList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.sxt.hbase.datePhoneList)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sxt_hbase_phone_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sxt_hbase_phone_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sxt_hbase_datePhoneList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sxt_hbase_datePhoneList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013phone.proto\022\rcom.sxt.hbase\"D\n\005phone\022\020\n" +
      "\010phoneNum\030\001 \002(\t\022\014\n\004time\030\002 \002(\t\022\r\n\005dpNum\030\003" +
      " \002(\t\022\014\n\004type\030\004 \002(\005\"8\n\rdatePhoneList\022\'\n\td" +
      "atePhone\030\001 \003(\0132\024.com.sxt.hbase.phone"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_sxt_hbase_phone_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_sxt_hbase_phone_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_sxt_hbase_phone_descriptor,
              new java.lang.String[] { "PhoneNum", "Time", "DpNum", "Type", });
          internal_static_com_sxt_hbase_datePhoneList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_sxt_hbase_datePhoneList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_sxt_hbase_datePhoneList_descriptor,
              new java.lang.String[] { "DatePhone", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
